version: '2'

services: 
    kong:
      image: kong
    #   depends_on: 
    #     - kong-database
      ports: 
        - 8000:8000
        - 8001:8001
        - 8443:8443
        - 7946:7946
        - 7946:7946/udp
      links: 
        - kong-database:kong-database
      environment: 
        KONG_DATABASE: cassandra
        KONG_CASSANDRA_CONTACT_POINTS: :kong-database
        KONG_PG_HOST: kong-database
    kong-database:
      image: cassandra:2.2
      ports: 
        - 9042:9042
      expose:
        - 9042