version: '2'

services: 
    kong:
      image: kong
    #   depends_on: 
    #     - kong-database
      ports: 
        - 8000:8000
        - 8001:8001
        - 8443:8443
        - 7946:7946
        - 7946:7946/udp
      links: 
        - kong-database:kong-database
      environment: 
        KONG_DATABASE: postgres
        KONG_CASSANDRA_CONTACT_POINTS: :kong-database
        KONG_PG_HOST: kong-database
    kong-database:
      image: postgres:9.4
      ports: 
        - 5432:5432
      environment:
        POSTGRES_USER: kong
        POSTGRES_DB: kong
    # Set http://kong:8001 or docker internal IP (ex 172.24.0.3:8001)
    kong-dashboard:
      image: pgbi/kong-dashboard
      ports:
        - 8080:8080
      links:
        - kong:kong